Gearbox
blockchain-etl/ethereum-etl-airflow pull request #709
Opened 2024-04-25 02:20 UTC by qshao-gauntlet

## What?
ie: Add support for uniswap contract events 

## How? 
ie: I used [abi-parser](https://nansen-contract-parser-prod.web.app/) or cli tools to build the table definitions

## Related PRs (optional)
PRs that are related to this or may need to be deployed before this PR

## Anything Else?

2024-04-29 13:17 UTC, kome12 requested changes
The CI/CD is currently failing because some of the name field has an empty string. Can you please add the name field?

2024-04-29 13:17 UTC, kome12 commented on dags/resources/stages/parse/table_definitions/gearbox/DegenNFTV3_event_NewCreditFacadeAdded.json
> +                    "name": "",
Will need to add a name for this field.

2024-04-29 13:17 UTC, kome12 commented on dags/resources/stages/parse/table_definitions/gearbox/DegenNFTV3_event_NewCreditFacadeAdded.json
> +                "name": "",
Will need to add a name for this field.

2024-04-29 13:17 UTC, kome12 commented on dags/resources/stages/parse/table_definitions/gearbox/DegenNFTV3_event_NewCreditFacadeRemoved.json
> +                    "name": "",
Will need to add a name for this field.

2024-04-29 13:17 UTC, kome12 commented on dags/resources/stages/parse/table_definitions/gearbox/DegenNFTV3_event_NewCreditFacadeRemoved.json
> +                "name": "",
Will need to add a name for this field.

2024-04-29 13:17 UTC, kome12 commented on dags/resources/stages/parse/table_definitions/gearbox/DegenNFTV3_event_NewMinterSet.json
> +                    "name": "",
Will need to add a name for this field.

2024-04-29 13:17 UTC, kome12 commented on dags/resources/stages/parse/table_definitions/gearbox/DegenNFTV3_event_NewMinterSet.json
> +                "name": "",
Will need to add a name for this field.

2024-05-19 18:31 UTC, zigzag2002 commented on dags/resources/stages/parse/table_definitions/gearbox/DegenNFTV3_event_NewCreditFacadeAdded.json
> +                    "name": "",
fixed these

2024-05-19 22:49 UTC, zigzag2002 approved these changes

2024-05-19 22:52 UTC, zigzag2002 commented
> The CI/CD is currently failing because some of the name field has an empty string. Can you please add the name field?

Added names for all events, please approve when you get the chance to look over the changes

2024-05-22 00:33 UTC, kome12 approved these changes

2024-05-22 00:34 UTC, merged